package ct;

import java.awt.*;
import java.io.*;
import javax.swing.event.*;
import java.util.*;
import javax.swing.ImageIcon;
public class CTAbout extends javax.swing.JFrame  implements HyperlinkListener {
  ResourceBundle bundle2;
  CTModerator ctm;
  public CTAbout(CTModerator ctm) {
    initComponents();
    bundle2 = java.util.ResourceBundle.getBundle("ct/Bundle");
    this.ctm=ctm;
        int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=800;
        int h2=600;

        setSize(w2,h2);
        setTitle(bundle2.getString("CTAbout.xy.msg1")+" V. "+ctm.version);

        if(!ctm.tutorMode) jTabbedPane1.remove(jPanel2);

        setLocation((width-w2)/2,(h-h2)/2);

        Image iconImage=new ImageIcon(getClass().getClassLoader().getResource("crtc_logo_t.gif")).getImage();
        setIconImage(iconImage);
        jEditorPane1.setEditable(false);
        jEditorPane1.addHyperlinkListener(this);
        jEditorPane2.setEditable(false);
        jEditorPane2.addHyperlinkListener(this);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle(null);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jEditorPane1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ct/Bundle"); 
        jTabbedPane1.addTab(bundle.getString("CTAbout.jPanel1.TabConstraints.tabTitle"), jPanel1); 

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(jEditorPane2);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));
        jPanel3.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getSize()+6f));
        jButton1.setText(bundle.getString("CTAbout.jButton1.text")); 
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton3.setFont(jButton3.getFont().deriveFont(jButton3.getFont().getSize()+6f));
        jButton3.setText(bundle.getString("CTAbout.jButton3.text")); 
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        jButton2.setFont(jButton2.getFont().deriveFont(jButton2.getFont().getSize()+6f));
        jButton2.setText(bundle.getString("CTAbout.jButton2.text")); 
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jPanel3.add(jPanel5);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab(bundle.getString("CTAbout.jPanel2.TabConstraints.tabTitle"), jPanel2); 

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
  setVisible(false);
}

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
  setVisible(false);

  ctm.p_toRegister();
}

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    setVisible(false);
  ctm.p_toActivateAgain();
}
public void hyperlinkUpdate(HyperlinkEvent e){
    if(e.getEventType() == HyperlinkEvent.EventType.ACTIVATED)  { 
        

         String webAddr=e.getURL().toString();
         if(webAddr.indexOf("http")==-1){
             webAddr=webAddr.substring(5);
             webAddr=webAddr.replace('/', File.separatorChar);
             webAddr=(new File(webAddr)).getAbsolutePath();
             webAddr="file:///"+webAddr.replace(File.separatorChar,'/');
         }

           ctm.openURL.open(webAddr);

    }
}
public void setPage1(String page){
   try{
          jEditorPane1.setPage(page);
   }catch(IOException e){e.printStackTrace();}
}
public void setPage2(String page){
   try{
          jEditorPane2.setPage(page);
   }catch(IOException e){e.printStackTrace();}
}

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jTabbedPane1;

}