
package ct;
import java.awt.*;
public class CTOptions extends javax.swing.JDialog {

  public CTOptions(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
            int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=600;
        int h2=420;

        setSize(w2,h2);

        setLocation((width-w2)/2,(h-h2)/2);

    setVisible(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ct/Bundle"); 
        setTitle(bundle.getString("CTOptions.title")); 
        getContentPane().setLayout(null);

        jCheckBox1.setText(bundle.getString("CTOptions.jCheckBox1.text")); 
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(40, 30, 200, 23);

        jLabel1.setText(bundle.getString("CTOptions.jLabel1.text")); 
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 160, 15);

        jTextField1.setText(bundle.getString("CTOptions.jTextField1.text")); 
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 60, 40, 21);

        jLabel2.setText(bundle.getString("CTOptions.jLabel2.text")); 
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 60, 140, 20);

        jButton1.setText(bundle.getString("CTOptions.jButton1.text")); 
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 100, 200, 30);

        jLabel3.setText(bundle.getString("CTOptions.jLabel3.text")); 
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 210, 140, 15);

        jLabel4.setText(bundle.getString("CTOptions.jLabel4.text")); 
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 230, 430, 30);

        jButton2.setText(bundle.getString("CTOptions.jButton2.text")); 
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 300, 100, 30);

        jButton3.setText(bundle.getString("CTOptions.jButton3.text")); 
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 300, 90, 30);

        pack();
    }

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

}

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
       this.setVisible(false);
    }

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;

}