
package ct;

import java.awt.*;
import java.io.*;
import javax.swing.*;
import java.util.*;
public class CTRegister extends javax.swing.JDialog implements Runnable{
  boolean isSleep=false;
  CTModerator moderator;
  Thread t=null;
  Vector waitV=new Vector();
  String prc="0",em="";
  public CTRegister(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    this.moderator=(CTModerator)parent;
    initComponents();
    String pFile="apps\\cr-tutor\\images\\paypal.jpg";
    String cFile="apps\\cr-tutor\\images\\creditcard.jpg";
    pFile=moderator.w.fileSeparator(pFile);
    cFile=moderator.w.fileSeparator(cFile);
    jButton1.setIcon(new javax.swing.ImageIcon(pFile)); 
    jButton2.setIcon(new javax.swing.ImageIcon(cFile)); 
            int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=700;
        int h2=350;

        setSize(w2,h2);

        setLocationRelativeTo(null);
        this.setVisible(true);

        Image iconImage=new ImageIcon(getClass().getClassLoader().getResource("crtc_logo_t.gif")).getImage();
        setIconImage(iconImage);
  }
  public void run(){
  while(true){
   while(waitV.size()>0){
     int type=Integer.parseInt((String)waitV.get(0));
     switch(type){
       case 1:
         String v[]=p_getVer();
         if(v!=null && v.length>13){

           jLabel1.setText("Registration Fee:  US$"+v[12]);
           prc=v[12];
           moderator.p_statuses[32]=v[12];

         }
         break;
       case 2:
         break;
     }
      waitV.remove(0);
    }
    try{
      isSleep=true;
      t.sleep(1000L * 3600L * 24L * 365L);
    } catch(InterruptedException e){}
    isSleep=false;
  }
}
  String getAnotherPrice(int modN,String price,double interval){
    String rc="http://cloud-rain.com/web/getAnotherPrice.jsp?price="+price+"&modn="+modN+"&interval="+interval;
    rc=moderator.w.ap.urltooneline(rc);
    if(rc.indexOf("price:")>-1 && rc.indexOf(":price")>-1){
      price=rc.substring(rc.indexOf("price:")+6,rc.indexOf(":price"));
    }
    return price;
  }
boolean p_chkInput(){
   em=jTextField1.getText().trim();
  if(em.length()<1) {JOptionPane.showMessageDialog(this, "Email is a must item."); return false;}
  if(!moderator.p_isValidEmailAddress2(em)) {JOptionPane.showMessageDialog(this, "\""+em+"\" not a correct email format!"); return false;}
  return true;
}
void p_getRC(){
   String addr="",iTitle="",iN="";
   addr="";
   iTitle="";
   iN="";
   String rc="http://cloud-rain.com/web/getRC.jsp?a="+moderator.w.e16(System.getProperty("user.country"))+"&t=1&p="+
            moderator.w.e16(prc)+"&e="+moderator.w.e16(em)+"&ap="+moderator.w.e16("1")+"&ia="+addr+"&it="+iTitle+"&in="+iN;
    rc=moderator.w.ap.urltooneline(rc);
    if(rc.indexOf("rc:")>-1 && rc.indexOf(":rc")>-1){
      rc=rc.substring(rc.indexOf("rc:")+3,rc.indexOf(":rc"));
      if(rc.length()>0){
        moderator.p_statuses[44]=moderator.format4.format(new Date());
        moderator.p_statuses[46]="";
        moderator.p_statuses[47]="";
        try{
	  FileOutputStream out = new FileOutputStream ("apps"+File.separator+"cr-tutor"+File.separator+"lib"+File.separator+"dll"+File.separator+"rk.dll");
	  byte [] b=rc.getBytes();
	  out.write(b);
	  out.close();
      }catch(IOException e){e.printStackTrace();}
    }
    } else {}
    if(rc.indexOf("rt:")>-1 && rc.indexOf(":rt")>-1){
      rc=rc.substring(rc.indexOf("rt:")+3,rc.indexOf(":rt"));
      if(rc.length()>0) moderator.p_statuses[44]=rc;
    }
}
String [] p_getVer(){
  String v=moderator.w.ap.urltooneline("http://cloud-rain.com/web/version_crtutor.txt");

  if(v.indexOf(",")==-1) v=moderator.w.d642(v);

  String v2[]=null;
  if(v.length()>0 && v.indexOf(",")>-1) {
    v2=moderator.w.csvLineToArray(v);
    if(v2.length>1) moderator.p_statuses[31]=v2[1];
  }

  return v2;
}
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ct/Bundle"); 
        setTitle(bundle.getString("CTRegister.title")); 

        jPanel1.setLayout(null);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+6));
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText(bundle.getString("CTRegister.jLabel1.text")); 
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 120, 350, 30);

        jButton1.setFont(jButton1.getFont());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(360, 170, 250, 40);

        jButton2.setFont(jButton2.getFont());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(360, 260, 250, 40);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()+6));
        jLabel3.setText(bundle.getString("CTRegister.jLabel3.text")); 
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 170, 320, 40);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+6));
        jLabel4.setText(bundle.getString("CTRegister.jLabel4.text")); 
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 260, 300, 30);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+6));
        jLabel2.setText(bundle.getString("CTRegister.jLabel2.text")); 
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 220, 50, 30);

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+6));
        jLabel5.setText(bundle.getString("CTRegister.jLabel5.text")); 
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 50, 150, 40);

        jTextField1.setBackground(new java.awt.Color(255, 204, 255));
        jTextField1.setFont(jTextField1.getFont().deriveFont(jTextField1.getFont().getSize()+6f));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(190, 50, 420, 40);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 20, 270, 0);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
  if(p_chkInput()) {

    moderator.openURL.open("https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=CFQ76DSVSXHLL");
    setVisible(false);
    p_getRC();
  }
}

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
  if(p_chkInput()) {

    moderator.openURL.open("https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=CFQ76DSVSXHLL");
    setVisible(false);
    p_getRC();
  }
}

  /**
   * @param args the command line arguments
   */

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;

}