
package ct;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.Iterator;
import java.util.ResourceBundle;
import java.util.TreeMap;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import y.ylib.ylib;

/**
 *
 * @author peter
 */
public class CTSlidesDialg extends javax.swing.JDialog {
  CTModerator moderator;
  ResourceBundle bundle2 = java.util.ResourceBundle.getBundle("ct/Bundle");
  public TreeMap tempSlides=null;
  public DefaultListModel listModel1=new DefaultListModel();
  public CTSlidesDialg(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    jList1.setModel(listModel1);
    this.moderator=(CTModerator)parent;
    tempSlides=moderator.slides;
        int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=680;
        int h2=400;

        setSize(w2,h2);

        setLocation((width-w2)/2,(h-h2)/2);

        Image iconImage=new ImageIcon(getClass().getClassLoader().getResource("crtc_logo_t.gif")).getImage();
        setIconImage(iconImage);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jButton8 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton10 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ct/Bundle"); 
    setTitle(bundle.getString("CTSlidesDialg.xy.msg1")); 
    getContentPane().setLayout(null);

    jButton1.setText(bundle.getString("CTSlidesDialg.jButton1.text")); 
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1);
    jButton1.setBounds(260, 300, 100, 23);

    jButton2.setText(bundle.getString("CTSlidesDialg.jButton2.text")); 
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton2);
    jButton2.setBounds(410, 300, 110, 23);

    jList1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jList1MouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jList1);

    getContentPane().add(jScrollPane1);
    jScrollPane1.setBounds(20, 40, 350, 240);

    jButton3.setText(bundle.getString("CTSlidesDialg.jButton3.text")); 
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton3);
    jButton3.setBounds(390, 220, 240, 23);

    jButton4.setText(bundle.getString("CTSlidesDialg.jButton4.text")); 
    jButton4.setToolTipText(bundle.getString("CTSlidesDialg.jButton4.toolTipText")); 
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton4);
    jButton4.setBounds(390, 40, 240, 23);

    jButton5.setText(bundle.getString("CTSlidesDialg.jButton5.text")); 
    jButton5.setToolTipText(bundle.getString("CTSlidesDialg.jButton5.toolTipText")); 
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton5);
    jButton5.setBounds(390, 130, 240, 23);

    jButton6.setText(bundle.getString("CTSlidesDialg.jButton6.text")); 
    jButton6.setToolTipText(bundle.getString("CTSlidesDialg.jButton6.toolTipText")); 
    jButton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton6ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton6);
    jButton6.setBounds(390, 70, 240, 23);

    jButton7.setText(bundle.getString("CTSlidesDialg.jButton7.text")); 
    jButton7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton7ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton7);
    jButton7.setBounds(390, 190, 240, 23);

    jLabel1.setText(bundle.getString("CTSlidesDialg.jLabel1.text")); 
    getContentPane().add(jLabel1);
    jLabel1.setBounds(20, 15, 100, 20);

    jButton8.setText(bundle.getString("CTSlidesDialg.jButton8.text")); 
    jButton8.setToolTipText(bundle.getString("CTSlidesDialg.jButton8.toolTipText")); 
    jButton8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton8ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton8);
    jButton8.setBounds(390, 100, 240, 23);

    jButton9.setText(bundle.getString("CTSlidesDialg.jButton9.text")); 
    jButton9.setToolTipText(bundle.getString("CTSlidesDialg.jButton9.toolTipText")); 
    jButton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton9ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton9);
    jButton9.setBounds(390, 160, 240, 23);

    jButton10.setText(bundle.getString("CTSlidesDialg.jButton10.text")); 
    jButton10.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton10ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton10);
    jButton10.setBounds(390, 250, 240, 23);

    pack();
  }

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    setVisible(false);
  }

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    updateFromList();
    moderator.sld_updateSlideList(false);
    setVisible(false);
  }

  private void jList1MouseClicked(java.awt.event.MouseEvent evt) {
    if(evt.getClickCount()==2){
      edit();
    }
  }

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {

   CTSlideAddWebZip dialog=new CTSlideAddWebZip(moderator,true);
   dialog.setVisible(true);
   updateList();
  }

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {

    CTSlideAddDir dialog=new CTSlideAddDir(moderator,true);
   dialog.setVisible(true);
   updateList();

  }

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {

      CTSlideAddZip dialog=new CTSlideAddZip(moderator,true);
   dialog.setVisible(true);
      updateList();

  }

  private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {

      CTSlideAddImage dialog=new CTSlideAddImage(moderator,true);
   dialog.setVisible(true);
      updateList();

  }

  private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {

   CTSlideAddWebImage dialog=new CTSlideAddWebImage(moderator,true);
   dialog.setVisible(true);
      updateList();

  }

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    String sel=(String)jList1.getSelectedValue();
    tempSlides.remove(sel);
    updateList();
  }

  private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
   edit();
  }

  private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
    String sel=(String)jList1.getSelectedValue();
    setVisible(false);
    updateFromList();
    moderator.sld_updateSlideList(false);
    moderator.cbb_slide.setSelectedItem(sel);
    moderator.sld_openSlide(sel);
  }
void edit(){
     String sel=(String)jList1.getSelectedValue();
   if(sel!=null){
     if(tempSlides.get(sel)!=null){
     String arr[]=ylib.csvlinetoarray((String)tempSlides.get(sel));
     String pw=arr[3];
     String pwencode=arr[4];
     if(sel.toLowerCase().trim().indexOf("http")==0){
       if(sel.toLowerCase().trim().endsWith(".zip")){
        CTSlideAddWebZip dialog=new CTSlideAddWebZip(moderator,true);
        dialog.setValue(sel,pw,pwencode);
        dialog.setVisible(true);
        updateList();
       } else {
        CTSlideAddWebImage dialog=new CTSlideAddWebImage(moderator,true);
        dialog.setValue(sel);
        dialog.setVisible(true);
        updateList();
       }
     } else if(sel.indexOf(".")>-1){
       if(sel.toLowerCase().trim().endsWith(".zip")){
        CTSlideAddZip dialog=new CTSlideAddZip(moderator,true);
        dialog.setValue(sel,pw,pwencode);
        dialog.setVisible(true);
        updateList();
       } else {
        CTSlideAddImage dialog=new CTSlideAddImage(moderator,true);
        dialog.setValue(sel);
        dialog.setVisible(true);
        updateList();
       }
     } else {
        CTSlideAddDir dialog=new CTSlideAddDir(moderator,true);
        dialog.setValue(sel);
        dialog.setVisible(true);
        updateList();
     }
     } else JOptionPane.showMessageDialog(null, sel+" "+bundle2.getString("CTSlidesDialg.xy.msg3"));
   } else JOptionPane.showMessageDialog(null, bundle2.getString("CTSlidesDialg.xy.msg2"));
}
  public void updateList(){
  String sel=(String)jList1.getSelectedValue();
  listModel1.removeAllElements();

  if(tempSlides.size()>0){
    Iterator it=tempSlides.keySet().iterator();
    for(;it.hasNext();){
      String key=(String)it.next();

      listModel1.addElement(key);
    }
    if(sel!=null){
      jList1.setSelectedValue(sel, true);
    } else jList1.setSelectedIndex(0);
  }
}
public void updateFromList(){
  

  moderator.slides=(TreeMap)tempSlides.clone();
}
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {

        

    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CTSlidesDialg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CTSlidesDialg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CTSlidesDialg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CTSlidesDialg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        CTSlidesDialg dialog = new CTSlidesDialg(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JList jList1;
  private javax.swing.JScrollPane jScrollPane1;

}