
package ct;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author peter
 */
public class CTSlideAddWebImage extends javax.swing.JDialog {

  CTModerator moderator;
  public CTSlideAddWebImage(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
            this.moderator=(CTModerator) parent;
        int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int h=Toolkit.getDefaultToolkit().getScreenSize().height-20;

        int w2=650;
        int h2=80;

        setSize(w2,h2);
        setLocation((width-w2)/2,(h-h2)/2);

        Image iconImage=new ImageIcon(getClass().getClassLoader().getResource("crtc_logo_t.gif")).getImage();
        setIconImage(iconImage);
        setTitle(moderator.bundle2.getString("CTSlidesDialg.xy.msg7"));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ct/Bundle"); 
    jLabel1.setText(bundle.getString("CTSlideAddWebImage.jLabel1.text")); 
    getContentPane().add(jLabel1);

    jTextField1.setToolTipText(bundle.getString("CTSlideAddWebImage.jTextField1.toolTipText")); 
    jTextField1.setPreferredSize(new java.awt.Dimension(306, 21));
    getContentPane().add(jTextField1);

    jButton1.setText(bundle.getString("CTSlideAddWebImage.jButton1.text")); 
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1);

    jButton2.setText(bundle.getString("CTSlideAddWebImage.jButton2.text")); 
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton2);

    pack();
  }

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    setVisible(false);
  }
public void setValue(String id){
  jTextField1.setText(id);
}
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    String key=jTextField1.getText().trim();
    if(key.length()>0){
    String data=key+",,*.*,,N,,0";
    moderator.sld_dialog.tempSlides.put(key, data);
    }
    setVisible(false);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {

        

    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CTSlideAddWebImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CTSlideAddWebImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CTSlideAddWebImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CTSlideAddWebImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        CTSlideAddWebImage dialog = new CTSlideAddWebImage(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField jTextField1;

}