
package ct;

/**
 *
 * @author 850136
 */
public class CTUpdate extends javax.swing.JDialog {

  /** Creates new form CTUpdate */
  public CTUpdate(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getSize()+6f));
        jButton1.setText("Cancel");
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 190, 80, 31);

        jButton2.setFont(jButton2.getFont().deriveFont(jButton2.getFont().getSize()+6f));
        jButton2.setText("Next");
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 190, 90, 31);

        jProgressBar1.setFont(jProgressBar1.getFont());
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(50, 140, 300, 19);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+6f));
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 40, 290, 23);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+6f));
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 290, 23);

        pack();
    }

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;

}